project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_API_TOKEN

base_path: "."
base_url: "https://api.crowdin.com"

files:
  - source: "/application/src/main/resources/locale/**/*.csv"
    translation: "/application/src/main/resources/locale/**/%original_file_name%"
    type: csv
    scheme: identifier,source_phrase,,de,es-ES,fr,pt-PT,ru,zh-CN
    languages_mapping:
      locale:
        de: de
        es-ES: es
        fr: fr
        pt-PT: pt
        ru: ru
        zh-CN: zh