project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_API_TOKEN

base_path: "."
base_url: "https://api.crowdin.com"
preserve_hierarchy: true
files:
  - source: "/application/src/main/resources/locale/**/*.csv"
    translation: "/application/src/main/resources/locale/**/%file_name%.%file_extension%"
    type: csv
    scheme: identifier,source_phrase,,de,es-ES,fr,pt-PT,ru,zh-CN
    first_line_contains_header: true
    languages_mapping:
      locale:
        de: de
        es-ES: es
        fr: fr
        pt-PT: pt
        ru: ru
        zh-CN: zh